=== Hajar-Oe/TP-XML/commande.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT shop (client,commande)+ >
<!ELEMENT client (nom, prenom,adresse)>
<!ATTLIST client numClient ID #REQUIRED>
    <!ELEMENT nom (#PCDATA)>
    <!ELEMENT prenom (#PCDATA)>
    <!ELEMENT adresse (#PCDATA)>
<!ELEMENT commande (date,ligne_commande*)>
     <!ATTLIST commande idClient IDREF #REQUIRED >
     <!ELEMENT date (jour,mois,annee)>
        <!ELEMENT jour (#PCDATA)>
        <!ELEMENT mois (#PCDATA)>
        <!ELEMENT annee (#PCDATA)>
     <!ELEMENT ligne_commande (produit,qte)*>
        <!ELEMENT produit EMPTY>
            <!ATTLIST produit 
            id ID #REQUIRED
            designation (PCDATA) #IMPLIED
            >
            <!ELEMENT qte (#PCDATA)>

=== Hajar-Oe/TP-XML/commande.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE shop SYSTEM "file:/C:/Users/Hajar%20Ousguine/OneDrive/Documents/Cours%20S3/XML%20M_Daaif/TP/commande.dtd">
<shop>
<client numClient="A12">
    <nom>Ousguine</nom>
    <prenom>Hajar</prenom>
    <adresse>SalÃ©</adresse>
</client>
<commande idClient="A12">
        <date>
            <jour>03</jour>
            <mois>Mars</mois>
            <annee>2020</annee>
        </date>
        <ligne_commande>
            <produit id="E23"/>
            <qte>2</qte>
        </ligne_commande>
</commande>
</shop>
